version: '3.1'
services:
  registry:
    image: registry:2
    volumes: 
      - registry:/var/lib/registry

nginx:
  image: nginx:alpine
  ports:
    - 5043:443
  links:
    - registry:registry
  volumes:
    - ./auth:/etc/nginx/conf.d
    - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  registry: