version: '3.1'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.1
    ports: [ 8080:8080 ]
    environment: 
      - KEYCLOAK_USER_FILE=/run/secrets/KEYCLOAK_USER
      - KEYCLOAK_PASSWORD_FILE=/run/secrets/KEYCLOAK_PWD
      - DB_VENDOR=mariadb
      - DB_ADDR=db
      - DB_PORT=3306
      - DB_DATABASE=keycloak
      - DB_USER_FILE=/run/secrets/KEYCLOAK_DB_USER
      - DB_PASSWORD_FILE=/run/secrets/KEYCLOAK_DB_PWD
    secrets:
      - KEYCLOAK_DB_USER
      - KEYCLOAK_DB_PWD
      - KEYCLOAK_PWD
      - KEYCLOAK_USER

secrets:
 KEYCLOAK_USER:
    external: true
  KEYCLOAK_PWD:
    external: true
 KEYCLOAK_DB_USER:
    external: true
  KEYCLOAK_DB_PWD:
    external: true